#!/bin/bash
PATH_PWD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

cd ${PATH_PWD}/libgpio
make -j$(nproc)
make install

cd ${PATH_PWD}/command
make -j$(nproc)
./install

cd ${PATH_PWD}/server
./install

