// SPDX-License-Identifier: GPL-2.0
/* Copyright(c) 2020 - 2023 Allwinner Technology Co.,Ltd. All rights reserved. */
/*
 * Copyright (c) 2021 liujuan1@allwinnertech.com
 */

// #include <sunxi-log.h>
// #include <linux/module.h>
// #include <linux/platform_device.h>
// #include <linux/of.h>
// #include <linux/of_device.h>
// #include <linux/pinctrl/pinctrl.h>
// #include <linux/io.h>

#include "pinctrl-sunxi.h"

static const struct sunxi_desc_pin sun55iw3_pins[] = {
/* Pin banks are: A B C D F G */

	/* bank A */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 0),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_RXD_DI[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 0),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 1),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_RXD_DI[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 1),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 2),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_RXD_DI[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 2),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 3),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_RXD_DI[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 3),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 4),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_TXD_DO[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 4),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 5),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_TXD_DO[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 5),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 6),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_TXD_DO[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 6),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 7),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_TXD_DO[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 7),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 8),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_CLKRX_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 8),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 10),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_RXDV_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 10),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_MDC_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 12),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_MD_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 12),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 13),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_TXEN_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 13),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 14),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_CLKTX_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 14),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(A, 18),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "GMAC0_CLKTX_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 18),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* bank B */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x3, "CPUS_I2C0_SCL_Di"),
		SUNXI_FUNCTION(0x4, "I2C0_SCL_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 0),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x3, "CPUS_I2C0_SDA_Di"),
		SUNXI_FUNCTION(0x4, "I2C0_SDA_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 1),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 6),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "OWA_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 6),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 7),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "//OWA_MCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 7),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 8),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "UART0_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 8),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 9),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "UART0_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 9),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "CPUS_UART0_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 10),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "CPUS_UART0_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 19),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DI[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 19),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 21),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "CPUS_FIR_DI"),
		SUNXI_FUNCTION(0x3, "IR_RX_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 21),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 22),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DI[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 22),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 23),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_BCLK_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 23),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 24),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_LRC_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 24),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 25),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DO[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 25),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 26),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DO[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 26),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 27),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DO[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 27),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 28),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_SD_DO[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 28),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 29),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "I2S0_MCLK_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 29),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* bank C */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_ALE_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 1),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_CEN_DO[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 3),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_REN_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 5),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_RB_DI[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 7),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 10),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_DQ_DO[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 10),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_DQ_DO[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 16),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_WPN_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 16),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 17),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_RE_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 17),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 18),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "NDFC0_DQSN_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 18),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* bank D */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 0),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[0]"),
		SUNXI_FUNCTION(0x3, "LVDS00_IN[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 0),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 1),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[1]"),
		SUNXI_FUNCTION(0x3, "LVDS00_IN[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 1),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[2]"),
		SUNXI_FUNCTION(0x3, "LVDS00_IN[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 2),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[3]"),
		SUNXI_FUNCTION(0x3, "LVDS00_IN[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 3),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[4]"),
		SUNXI_FUNCTION(0x3, "LVDS00_IN[4]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 4),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[5]"),
		SUNXI_FUNCTION(0x3, "LVDS01_IN[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 5),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[6]"),
		SUNXI_FUNCTION(0x3, "LVDS01_IN[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 6),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[7]"),
		SUNXI_FUNCTION(0x3, "LVDS01_IN[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 7),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 8),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[8]"),
		SUNXI_FUNCTION(0x3, "LVDS01_IN[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 8),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 9),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[9]"),
		SUNXI_FUNCTION(0x3, "LVDS01_IN[4]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 9),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[10]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 10),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[11]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[12]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 12),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[13]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 13),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[14]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 14),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[15]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 15),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 16),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[16]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 16),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 17),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[17]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 17),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[18]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 18),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[19]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 19),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[20]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 20),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[21]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 21),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[22]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 22),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 23),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[23]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 23),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 24),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[24]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 24),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 25),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[25]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 25),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 26),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[26]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 26),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 27),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DPSS_RGB0_DO[27]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 27),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* bank F */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CDAT_DI[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 0),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CDAT_DI[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 1),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CDAT_DI[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 2),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CDAT_DI[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 3),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CCMD_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 4),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD0_CCLK_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 5),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 9),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DMIC_CLK_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 9),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "SPIF_DQS_DI"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQS_OE"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 16),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 16),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 17),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[1]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 17),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 18),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[2]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 18),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 19),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[3]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 19),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 20),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[4]"),
		SUNXI_FUNCTION(0x3, "SPIF_DQ4_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[4]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 20),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 21),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[5]"),
		SUNXI_FUNCTION(0x3, "SPIF_DQ5_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[5]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 21),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 22),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[6]"),
		SUNXI_FUNCTION(0x3, "SPIF_DQ6_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[6]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 22),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 23),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CDAT_DO[7]"),
		SUNXI_FUNCTION(0x3, "SPIF_DQ7_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[7]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 23),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 24),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CCMD_DI"),
		SUNXI_FUNCTION(0x3, "SPIF_MOSI_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_CLE_DO"),
		SUNXI_FUNCTION(0x5, "SPI0_MOSI_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 24),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 25),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SD2_CCLK_DO"),
		SUNXI_FUNCTION(0x3, "SPIF_SS_DO[0]"),
		SUNXI_FUNCTION(0x4, "NDFC0_RB_DI[0]"),
		SUNXI_FUNCTION(0x5, "SPI0_SS_DO[0]"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 25),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 26),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x3, "SPIF_HOLD_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[0]"),
		SUNXI_FUNCTION(0x5, "SPI0_HOLD_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 26),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 27),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "SDC2"),           /* sd2_ds_di (for sh400) */
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 27),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 28),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DMIC_D0_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 28),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 29),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x3, "SPIF_MISO_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_CEN_DO[0]"),
		SUNXI_FUNCTION(0x5, "SPI0_MISO_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 29),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 30),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x3, "SPIF_WP_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_DQ_DO[1]"),
		SUNXI_FUNCTION(0x5, "SPI0_WP_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 30),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 31),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x3, "SPIF_SCK_DO"),
		SUNXI_FUNCTION(0x4, "NDFC0_WEN_DO"),
		SUNXI_FUNCTION(0x5, "SPI0_SCK_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 31),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* bank G */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x5, "LEDC_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 0),   /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x5, "IR_TX_DO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 11),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 26),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DMIC_D3_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 26),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 28),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DMIC_D2_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 28),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 30),
		SUNXI_FUNCTION(0x0, "IN"),       
		SUNXI_FUNCTION(0x1, "OUT"),      
		SUNXI_FUNCTION(0x2, "DMIC_D1_DI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 30),  /* eint */
		SUNXI_FUNCTION(0xf, "OFF")),  
	/* Pin banks are: B C D F G H I J K */
	/* bank B */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART2_TX"),
		SUNXI_FUNCTION(0x3, "SPI2_CS"),
		SUNXI_FUNCTION(0x4, "JTAG_MS"),
		SUNXI_FUNCTION(0x5, "LCD0_D0"),
		SUNXI_FUNCTION(0x6, "PWM0-6"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART2_RX"),
		SUNXI_FUNCTION(0x3, "SPI2_CLK"),
		SUNXI_FUNCTION(0x4, "JTAG_CK"),
		SUNXI_FUNCTION(0x5, "LCD0_D1"),
		SUNXI_FUNCTION(0x6, "PWM0-7"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART2_RTS"),
		SUNXI_FUNCTION(0x3, "SPI2_MOSI"),
		SUNXI_FUNCTION(0x4, "JTAG_DO"),
		SUNXI_FUNCTION(0x5, "LCD0_D8"),
		SUNXI_FUNCTION(0x6, "PIN_TEST"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART2_CTS"),
		SUNXI_FUNCTION(0x3, "SPI2_MISO"),
		SUNXI_FUNCTION(0x4, "JTAG_DI"),
		SUNXI_FUNCTION(0x5, "LCD0_D9"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C1_SCL"),
		SUNXI_FUNCTION(0x3, "I2S0_MCLK"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA2"),
		SUNXI_FUNCTION(0x5, "PWM0-8"),
		SUNXI_FUNCTION(0x6, "HSCL"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C1_SDA"),
		SUNXI_FUNCTION(0x3, "I2S0_BCLK"),
		SUNXI_FUNCTION(0x4, "TRACE_CLK"),
		SUNXI_FUNCTION(0x5, "PWM0-9"),
		SUNXI_FUNCTION(0x6, "HSDA"),
		SUNXI_FUNCTION(0x7, "PIN_TEST"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S0_LRCK"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA0"),
		SUNXI_FUNCTION(0x5, "PWM0-10"),
		SUNXI_FUNCTION(0x6, "HCEC"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "OWA_IN"),
		SUNXI_FUNCTION(0x3, "I2S0_DOUT0"),
		SUNXI_FUNCTION(0x4, "I2S0_DIN1"),
		SUNXI_FUNCTION(0x5, "LCD0_D16"),
		SUNXI_FUNCTION(0x6, "PWM0-11"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "OWA_OUT"),
		SUNXI_FUNCTION(0x3, "I2S0_DIN0"),
		SUNXI_FUNCTION(0x4, "I2S0_DOUT1"),
		SUNXI_FUNCTION(0x5, "LCD0_D17"),
		SUNXI_FUNCTION(0x6, "PWM0-0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART0_TX"),
		SUNXI_FUNCTION(0x3, "I2C0_SCL"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA1"),
		SUNXI_FUNCTION(0x5, "I2S0_DIN2"),
		SUNXI_FUNCTION(0x6, "I2S0_DOUT2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART0_RX"),
		SUNXI_FUNCTION(0x3, "I2C0_SDA"),
		SUNXI_FUNCTION(0x4, "PWM0-1"),
		SUNXI_FUNCTION(0x5, "I2S0_DIN3"),
		SUNXI_FUNCTION(0x6, "I2S0_DOUT3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C5_SCL"),
		SUNXI_FUNCTION(0x3, "UART7_RTS"),
		SUNXI_FUNCTION(0x4, "SPI1_CS0"),
		SUNXI_FUNCTION(0x5, "PWM0-2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C5_SDA"),
		SUNXI_FUNCTION(0x3, "UART7_CTS"),
		SUNXI_FUNCTION(0x4, "SPI1_CLK"),
		SUNXI_FUNCTION(0x5, "PWM0-3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SCL"),
		SUNXI_FUNCTION(0x3, "UART7_TX"),
		SUNXI_FUNCTION(0x4, "SPI1_MOSI"),
		SUNXI_FUNCTION(0x5, "PWM0-4"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(B, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SDA"),
		SUNXI_FUNCTION(0x3, "UART7_RX"),
		SUNXI_FUNCTION(0x4, "SPI1_MISO"),
		SUNXI_FUNCTION(0x5, "PWM0-5"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 0, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* bank C */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_WE"),
		SUNXI_FUNCTION(0x3, "SDC2_DS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_ALE"),
		SUNXI_FUNCTION(0x3, "SDC2_RST"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_CLE"),
		SUNXI_FUNCTION(0x4, "SPI0_MOSI"),
		SUNXI_FUNCTION(0x5, "SPIF_MOSI_IO0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_CE1"),
		SUNXI_FUNCTION(0x4, "SPI0_CS0"),
		SUNXI_FUNCTION(0x5, "SPIF_CS0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_CE0"),
		SUNXI_FUNCTION(0x4, "SPI0_MISO"),
		SUNXI_FUNCTION(0x5, "SPIF_MISO_IO1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_RE"),
		SUNXI_FUNCTION(0x3, "SDC2_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_RB0"),
		SUNXI_FUNCTION(0x3, "SDC2_CMD"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_RB1"),
		SUNXI_FUNCTION(0x4, "SPI0_CS1"),
		SUNXI_FUNCTION(0x5, "SPIF_DQS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ7"),
		SUNXI_FUNCTION(0x3, "SDC2_D3"),
		SUNXI_FUNCTION(0x5, "SPIF_IO7"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ6"),
		SUNXI_FUNCTION(0x3, "SDC2_D4"),
		SUNXI_FUNCTION(0x5, "SPIF_IO6"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ5"),
		SUNXI_FUNCTION(0x3, "SDC2_D0"),
		SUNXI_FUNCTION(0x5, "SPIF_IO5"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ4"),
		SUNXI_FUNCTION(0x3, "SDC2_D5"),
		SUNXI_FUNCTION(0x5, "SPIF_IO4"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQS"),
		SUNXI_FUNCTION(0x4, "SPI0_CLK"),
		SUNXI_FUNCTION(0x5, "SPIF_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ3"),
		SUNXI_FUNCTION(0x3, "SDC2_D1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ2"),
		SUNXI_FUNCTION(0x3, "SDC2_D6"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND_DQ1"),
		SUNXI_FUNCTION(0x3, "SDC2_D2"),
		SUNXI_FUNCTION(0x4, "SPI0_WP"),
		SUNXI_FUNCTION(0x5, "SPIF"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(C, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "NAND"),
		SUNXI_FUNCTION(0x3, "SDC2"),
		SUNXI_FUNCTION(0x4, "SPI0_HOLD"),
		SUNXI_FUNCTION(0x5, "SPIF"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 1, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* bank D */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D2"),
		SUNXI_FUNCTION(0x3, "LVDS0_D0P"),
		SUNXI_FUNCTION(0x4, "DSI0_DP0"),
		SUNXI_FUNCTION(0x5, "PWM0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D3"),
		SUNXI_FUNCTION(0x3, "LVDS0_D0N"),
		SUNXI_FUNCTION(0x4, "DSI0_DM0"),
		SUNXI_FUNCTION(0x5, "PWM0-1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D4"),
		SUNXI_FUNCTION(0x3, "LVDS0_D1P"),
		SUNXI_FUNCTION(0x4, "DSI0_DP1"),
		SUNXI_FUNCTION(0x5, "PWM0-2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D5"),
		SUNXI_FUNCTION(0x3, "LVDS0_D1N"),
		SUNXI_FUNCTION(0x4, "DSI0_DM1"),
		SUNXI_FUNCTION(0x5, "PWM0-3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D6"),
		SUNXI_FUNCTION(0x3, "LVDS0_D2P"),
		SUNXI_FUNCTION(0x4, "DSI0_CKP"),
		SUNXI_FUNCTION(0x5, "PWM0-4"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D7"),
		SUNXI_FUNCTION(0x3, "LVDS0_D2N"),
		SUNXI_FUNCTION(0x4, "DSI0_CKM"),
		SUNXI_FUNCTION(0x5, "PWM0-5"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D10"),
		SUNXI_FUNCTION(0x3, "LVDS0_CKP"),
		SUNXI_FUNCTION(0x4, "DSI0_DP2"),
		SUNXI_FUNCTION(0x5, "PWM0-6"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D11"),
		SUNXI_FUNCTION(0x3, "LVDS0_CKN"),
		SUNXI_FUNCTION(0x4, "DSI0_DM2"),
		SUNXI_FUNCTION(0x5, "PWM0-7"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D12"),
		SUNXI_FUNCTION(0x3, "LVDS0_D3P"),
		SUNXI_FUNCTION(0x4, "DSI0_DP3"),
		SUNXI_FUNCTION(0x5, "PWM0-8"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D13"),
		SUNXI_FUNCTION(0x3, "LVDS0_D3N"),
		SUNXI_FUNCTION(0x4, "DSI0_DM3"),
		SUNXI_FUNCTION(0x5, "PWM0-9"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D14"),
		SUNXI_FUNCTION(0x3, "LVDS1_D0P"),
		SUNXI_FUNCTION(0x4, "DSI1_DP0"),
		SUNXI_FUNCTION(0x5, "PWM0-10"),
		SUNXI_FUNCTION(0x6, "SPI1_CS0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D15"),
		SUNXI_FUNCTION(0x3, "LVDS1_D0N"),
		SUNXI_FUNCTION(0x4, "DSI1_DM0"),
		SUNXI_FUNCTION(0x5, "PWM0-11"),
		SUNXI_FUNCTION(0x6, "SPI1_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D18"),
		SUNXI_FUNCTION(0x3, "LVDS1_D1P"),
		SUNXI_FUNCTION(0x4, "DSI1_DP1"),
		SUNXI_FUNCTION(0x5, "PWM0-12"),
		SUNXI_FUNCTION(0x6, "SPI1_MOSI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D19"),
		SUNXI_FUNCTION(0x3, "LVDS1_D1N"),
		SUNXI_FUNCTION(0x4, "DSI1_DM1"),
		SUNXI_FUNCTION(0x5, "PWM0-13"),
		SUNXI_FUNCTION(0x6, "SPI1_MISO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D20"),
		SUNXI_FUNCTION(0x3, "LVDS1_D2P"),
		SUNXI_FUNCTION(0x4, "DSI1_CKP"),
		SUNXI_FUNCTION(0x5, "PWM0-14"),
		SUNXI_FUNCTION(0x6, "UART3_TX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D21"),
		SUNXI_FUNCTION(0x3, "LVDS1_D2N"),
		SUNXI_FUNCTION(0x4, "DSI1_CKM"),
		SUNXI_FUNCTION(0x5, "PWM0-15"),
		SUNXI_FUNCTION(0x6, "UART3_RX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D22"),
		SUNXI_FUNCTION(0x3, "LVDS1_CKP/PLL_Test_ckp"),
		SUNXI_FUNCTION(0x4, "DSI1_DP2"),
		SUNXI_FUNCTION(0x5, "PWM1-0"),
		SUNXI_FUNCTION(0x6, "UART3_RTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 17),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_D23"),
		SUNXI_FUNCTION(0x3, "LVDS1_CKN/PLL_Test_ckn"),
		SUNXI_FUNCTION(0x4, "DSI1_DM2"),
		SUNXI_FUNCTION(0x5, "PWM1-1"),
		SUNXI_FUNCTION(0x6, "UART3_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 17),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 18),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_CLK"),
		SUNXI_FUNCTION(0x3, "LVDS1_D3P"),
		SUNXI_FUNCTION(0x4, "DSI1_DP3"),
		SUNXI_FUNCTION(0x5, "PWM1-2"),
		SUNXI_FUNCTION(0x6, "UART4_TX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 18),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 19),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_DE"),
		SUNXI_FUNCTION(0x3, "LVDS1_D3N"),
		SUNXI_FUNCTION(0x4, "DSI1_DM3"),
		SUNXI_FUNCTION(0x5, "PWM1-3"),
		SUNXI_FUNCTION(0x6, "UART4_RX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 19),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 20),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_HSYNC"),
		SUNXI_FUNCTION(0x3, "PWM0-2"),
		SUNXI_FUNCTION(0x4, "UART2_TX"),
		SUNXI_FUNCTION(0x5, "UART7_RTS"),
		SUNXI_FUNCTION(0x6, "UART4_RTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 20),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 21),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD0_VSYNC"),
		SUNXI_FUNCTION(0x3, "PWM0-3"),
		SUNXI_FUNCTION(0x4, "UART2_RX"),
		SUNXI_FUNCTION(0x5, "UART7_CTS"),
		SUNXI_FUNCTION(0x6, "UART4_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 21),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 22),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "PWM0-1"),
		SUNXI_FUNCTION(0x3, "SPI1_HOLD"),
		SUNXI_FUNCTION(0x4, "UART2_RTS"),
		SUNXI_FUNCTION(0x5, "UART7_TX"),
		SUNXI_FUNCTION(0x6, "I2C0_SCK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 22),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(D, 23),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "PWM0"),
		SUNXI_FUNCTION(0x3, "SPI1_WP"),
		SUNXI_FUNCTION(0x4, "UART2_CTS"),
		SUNXI_FUNCTION(0x5, "UART7_RX"),
		SUNXI_FUNCTION(0x6, "I2C0_SDA"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 2, 23),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* bank E */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MIPI_MCLK0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C2_SCL"),
		SUNXI_FUNCTION(0x3, "UART4_TX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C2_SDA"),
		SUNXI_FUNCTION(0x3, "UART4_RX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C3_SCL"),
		SUNXI_FUNCTION(0x3, "UART4_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C3_SDA"),
		SUNXI_FUNCTION(0x3, "UART4_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MIPI_MCLK1"),
		SUNXI_FUNCTION(0x3, "PLL_LOCK_DBG"),
		SUNXI_FUNCTION(0x4, "I2S2_MCLK"),
		SUNXI_FUNCTION(0x5, "LEDC"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "BIST_RESULT0"),
		SUNXI_FUNCTION(0x4, "I2S2_BCLK"),
		SUNXI_FUNCTION(0x5, "LCD0_TRIG"),
		SUNXI_FUNCTION(0x6, "NCSI_D8"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "BIST_RESULT1"),
		SUNXI_FUNCTION(0x4, "I2S2_LRCK"),
		SUNXI_FUNCTION(0x5, "LCD1_TRIG"),
		SUNXI_FUNCTION(0x6, "NCSI_D9"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "BIST_RESULT2"),
		SUNXI_FUNCTION(0x4, "I2S2_DOUT0"),
		SUNXI_FUNCTION(0x5, "LCD2_TRIG"),
		SUNXI_FUNCTION(0x6, "NCSI_D10"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "BIST_RESULT3"),
		SUNXI_FUNCTION(0x4, "I2S2_DIN0"),
		SUNXI_FUNCTION(0x6, "NCSI_D11"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MIPI_MCLK3"),
		SUNXI_FUNCTION(0x3, "PWM0-3"),
		SUNXI_FUNCTION(0x6, "NCSI_D12"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C1_SCL"),
		SUNXI_FUNCTION(0x3, "UART5_RTS"),
		SUNXI_FUNCTION(0x4, "SPI2_CS"),
		SUNXI_FUNCTION(0x5, "UART6_TX"),
		SUNXI_FUNCTION(0x6, "NCSI_D13"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C1_SDA"),
		SUNXI_FUNCTION(0x3, "UART5_CTS"),
		SUNXI_FUNCTION(0x4, "SPI2_CLK"),
		SUNXI_FUNCTION(0x5, "UART6_RX"),
		SUNXI_FUNCTION(0x6, "NCSI_D14"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SCL"),
		SUNXI_FUNCTION(0x3, "UART5_TX"),
		SUNXI_FUNCTION(0x4, "SPI2_MOSI"),
		SUNXI_FUNCTION(0x5, "UART6_RTS"),
		SUNXI_FUNCTION(0x6, "CSI_SM_VS0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SDA"),
		SUNXI_FUNCTION(0x3, "UART5_RX"),
		SUNXI_FUNCTION(0x4, "SPI2_MISO"),
		SUNXI_FUNCTION(0x5, "UART6_CTS"),
		SUNXI_FUNCTION(0x6, "CSI_SM_VS1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(E, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MIPI_MCLK2"),
		SUNXI_FUNCTION(0x3, "PWM0-2"),
		SUNXI_FUNCTION(0x6, "NCSI_D15"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 3, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks F */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_D1"),
		SUNXI_FUNCTION(0x3, "JTAG_MS"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA2"),
		SUNXI_FUNCTION(0x5, "I2S3_DIN0"),
		SUNXI_FUNCTION(0x6, "I2S3_DOUT1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_D0"),
		SUNXI_FUNCTION(0x3, "JTAG_DI"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA1"),
		SUNXI_FUNCTION(0x5, "I2S3_DOUT0"),
		SUNXI_FUNCTION(0x6, "I2S3_DIN1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_CLK"),
		SUNXI_FUNCTION(0x3, "UART0_TX"),
		SUNXI_FUNCTION(0x5, "I2S3_DIN2"),
		SUNXI_FUNCTION(0x6, "I2S3_DOUT2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_CMD"),
		SUNXI_FUNCTION(0x3, "JTAG_DO"),
		SUNXI_FUNCTION(0x4, "TRACE_DATA0"),
		SUNXI_FUNCTION(0x5, "I2S3_LRCK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_D3"),
		SUNXI_FUNCTION(0x3, "UART_RX"),
		SUNXI_FUNCTION(0x5, "I2S3_DIN3"),
		SUNXI_FUNCTION(0x6, "I2S3_DOUT3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC0_D2"),
		SUNXI_FUNCTION(0x3, "JTAG_CK"),
		SUNXI_FUNCTION(0x4, "TRACE_CLK"),
		SUNXI_FUNCTION(0x5, "I2S3_BCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(F, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x5, "I2S3_MCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 4, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks G */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_CMD"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_D0"),
		SUNXI_FUNCTION(0x3, "PCIE_PERSTN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_D1"),
		SUNXI_FUNCTION(0x3, "PCIE_WAKEN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_D2"),
		SUNXI_FUNCTION(0x3, "PCIE_CLKREQN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "SDC1_D3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART1_TX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART1_RX"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART1_RTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART1_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S1_MCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S1_BCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S1_LRCK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S1_DOUT0"),
		SUNXI_FUNCTION(0x4, "I2S1_DIN1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(G, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S1_DIN0"),
		SUNXI_FUNCTION(0x4, "I2S1_DOUT1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 5, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks H */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C0_SCL"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD1/RMii0_rxd1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C0_SCL"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD1/RMii0_rxd1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C0_SCL"),
		SUNXI_FUNCTION(0x3, "CPU_CUR_W"),
		SUNXI_FUNCTION(0x4, "I2S2_DIN3"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXCTL/Rmii0_crs_dv"),
		SUNXI_FUNCTION(0x6, "I2S2_DOUT3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C0_SDA"),
		SUNXI_FUNCTION(0x3, "CIR_OUT"),
		SUNXI_FUNCTION(0x4, "I2S2_DIN2"),
		SUNXI_FUNCTION(0x5, "RGMMII0_CLKIN/Rmii0_rxer"),
		SUNXI_FUNCTION(0x6, "I2S2_DOUT2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_TX"),
		SUNXI_FUNCTION(0x3, "SPI1_CS0"),
		SUNXI_FUNCTION(0x4, "CPU_CUR_W"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD1/RMii0_rxd1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_RX"),
		SUNXI_FUNCTION(0x3, "SPI1_CLK"),
		SUNXI_FUNCTION(0x4, "LEDC"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD0/RMii0_rxd0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_RTS"),
		SUNXI_FUNCTION(0x3, "SPI1_MOSI"),
		SUNXI_FUNCTION(0x4, "OWA_IN"),
		SUNXI_FUNCTION(0x5, "RGMMII0_TXCK/RMii0_txck"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_CTS"),
		SUNXI_FUNCTION(0x3, "SPI1_MISO"),
		SUNXI_FUNCTION(0x4, "OWA_OUT"),
		SUNXI_FUNCTION(0x5, "RGMMII0_TXCTL/Rmii0_txen"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "DMIC_CLK"),
		SUNXI_FUNCTION(0x3, "SPI2_CS"),
		SUNXI_FUNCTION(0x4, "I2S2_MCLK"),
		SUNXI_FUNCTION(0x5, "I2S2_DIN2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "DMIC_DATA0"),
		SUNXI_FUNCTION(0x3, "SPI2_CLK"),
		SUNXI_FUNCTION(0x4, "I2S2_BCLK"),
		SUNXI_FUNCTION(0x5, "MDC0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "DMIC_DATA1"),
		SUNXI_FUNCTION(0x3, "SPI2_MOSI"),
		SUNXI_FUNCTION(0x4, "I2S2_LRCK"),
		SUNXI_FUNCTION(0x5, "MDIO0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "DMIC_DATA2"),
		SUNXI_FUNCTION(0x3, "SPI2_MISO"),
		SUNXI_FUNCTION(0x4, "I2S2_DOUT0"),
		SUNXI_FUNCTION(0x5, "I2S2_DIN1"),
		SUNXI_FUNCTION(0x6, "PCIE_PERSTN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "DMIC_DATA3"),
		SUNXI_FUNCTION(0x3, "SPI2_SCK"),
		SUNXI_FUNCTION(0x4, "I2S2_DIN0"),
		SUNXI_FUNCTION(0x5, "I2S2_DOUT1"),
		SUNXI_FUNCTION(0x6, "PCIE_WAKEN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2C3_SDA"),
		SUNXI_FUNCTION(0x4, "I2S3_MCLK"),
		SUNXI_FUNCTION(0x5, "EPHY0_25"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x4, "I2S3_MCLK"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD3/RMii0_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x4, "I2S3_LRCK"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXD2/RMii0_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S3_DOUT0"),
		SUNXI_FUNCTION(0x4, "I2S3_DIN1"),
		SUNXI_FUNCTION(0x5, "RGMMII0_RXCK/RMii0_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 17),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x3, "I2S3_DOUT1"),
		SUNXI_FUNCTION(0x4, "I2S3_DIN0"),
		SUNXI_FUNCTION(0x5, "RGMMII0_TXD3/RMii0_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 17),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 18),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "CIR_OUT"),
		SUNXI_FUNCTION(0x3, "I2S3_DOUT2"),
		SUNXI_FUNCTION(0x4, "I2S3_DIN2"),
		SUNXI_FUNCTION(0x5, "RGMMII0_TXD2/RMii0_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 18),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(H, 19),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "CIR_OUT"),
		SUNXI_FUNCTION(0x3, "I2S3_DOUT3"),
		SUNXI_FUNCTION(0x4, "I2S3_DIN3"),
		SUNXI_FUNCTION(0x5, "LEDC"),
		SUNXI_FUNCTION(0x6, "PCIE_CLKREQN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 6, 19),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks I */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SCL"),
		SUNXI_FUNCTION(0x3, "UART4_TX"),
		SUNXI_FUNCTION(0x4, "PWM0-1"),
		SUNXI_FUNCTION(0x5, "I2S3_DIN3"),
		SUNXI_FUNCTION(0x6, "I2S2_DOUT3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C4_SDA"),
		SUNXI_FUNCTION(0x3, "UART4_RX"),
		SUNXI_FUNCTION(0x4, "PWM0-2"),
		SUNXI_FUNCTION(0x5, "I2S3_DIN2"),
		SUNXI_FUNCTION(0x6, "I2S2_DOUT2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART5_TX"),
		SUNXI_FUNCTION(0x3, "SPI1_CS0"),
		SUNXI_FUNCTION(0x4, "PWM0-3"),
		SUNXI_FUNCTION(0x5, "I2S2_BCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART5_RX"),
		SUNXI_FUNCTION(0x3, "SPI1_CLK"),
		SUNXI_FUNCTION(0x4, "PWM0-4"),
		SUNXI_FUNCTION(0x5, "I2S2_LRCK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART5_RTS"),
		SUNXI_FUNCTION(0x3, "SPI1_MOSI"),
		SUNXI_FUNCTION(0x4, "PWM0-5"),
		SUNXI_FUNCTION(0x5, "I2S2_DOUT0"),
		SUNXI_FUNCTION(0x6, "I2S2_DIN1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART5_CTS"),
		SUNXI_FUNCTION(0x3, "SPI1_MISO"),
		SUNXI_FUNCTION(0x4, "PWM0-6"),
		SUNXI_FUNCTION(0x5, "I2S2_DIN0"),
		SUNXI_FUNCTION(0x6, "I2S2_DOUT1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART6_TX"),
		SUNXI_FUNCTION(0x3, "UART4_RTS"),
		SUNXI_FUNCTION(0x4, "PWM0-7"),
		SUNXI_FUNCTION(0x5, "SPI2_CS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART6_RX"),
		SUNXI_FUNCTION(0x3, "UART4_CTS"),
		SUNXI_FUNCTION(0x4, "PWM0-8"),
		SUNXI_FUNCTION(0x5, "SPI2_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C5_SCL"),
		SUNXI_FUNCTION(0x3, "CIR_IN"),
		SUNXI_FUNCTION(0x4, "PWM0-9"),
		SUNXI_FUNCTION(0x5, "SPI2_MOSI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "I2C5_SDA"),
		SUNXI_FUNCTION(0x3, "DMIC_DATA2"),
		SUNXI_FUNCTION(0x4, "PWM0-10"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "OWA_OUT"),
		SUNXI_FUNCTION(0x3, "DMIC_DATA1"),
		SUNXI_FUNCTION(0x4, "PWM0-11"),
		SUNXI_FUNCTION(0x5, "I2S2_MCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_TX"),
		SUNXI_FUNCTION(0x3, "DMIC_DATA0"),
		SUNXI_FUNCTION(0x4, "PWM0-12"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_RX"),
		SUNXI_FUNCTION(0x4, "PWM0-13"),
		SUNXI_FUNCTION(0x5, "SPI2_MISO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART6_CTS"),
		SUNXI_FUNCTION(0x3, "DMIC_DATA3"),
		SUNXI_FUNCTION(0x4, "PWM0-14"),
		SUNXI_FUNCTION(0x5, "I2S2_MCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART6_RTS"),
		SUNXI_FUNCTION(0x3, "DMIC_CLK"),
		SUNXI_FUNCTION(0x4, "PWM0-15"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_RTS"),
		SUNXI_FUNCTION(0x3, "I2C2_SCL"),
		SUNXI_FUNCTION(0x4, "PWM1-0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(I, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "UART3_CTS"),
		SUNXI_FUNCTION(0x3, "I2C2_SDA"),
		SUNXI_FUNCTION(0x4, "PWM1-1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 7, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks J */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D0"),
		SUNXI_FUNCTION(0x3, "LVDS2_D0P"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXD1/RMii1_rxd1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D1"),
		SUNXI_FUNCTION(0x3, "LVDS2_D0N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXD0/RMii1_rxd0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D2"),
		SUNXI_FUNCTION(0x3, "LVDS2_D1P"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXCTL/Rmii1_crs_dv"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D3"),
		SUNXI_FUNCTION(0x3, "LVDS2_D1N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_CLKIN/Rmii1_rxer"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D4"),
		SUNXI_FUNCTION(0x3, "LVDS2_D2P"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXD1/RMii1_txd1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D5"),
		SUNXI_FUNCTION(0x3, "LVDS2_D2N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXD0/RMii1_txd0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D6"),
		SUNXI_FUNCTION(0x3, "LVDS2_CKP"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXCK/RMii1_txck"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D7"),
		SUNXI_FUNCTION(0x3, "LVDS2_CKN"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXCTL/Rmii1_txen"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D8"),
		SUNXI_FUNCTION(0x3, "LVDS2_D3P"),
		SUNXI_FUNCTION(0x5, "MDC1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D9"),
		SUNXI_FUNCTION(0x3, "LVDS2_D3N"),
		SUNXI_FUNCTION(0x5, "MDIO1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D10"),
		SUNXI_FUNCTION(0x3, "LVDS3_D0P"),
		SUNXI_FUNCTION(0x5, "EPHY1_25"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D11"),
		SUNXI_FUNCTION(0x3, "LVDS3_D0N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXD3/RMii1_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D12"),
		SUNXI_FUNCTION(0x3, "LVDS3_D1P"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXD2/RMii1_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D13"),
		SUNXI_FUNCTION(0x3, "LVDS3_D1N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_RXCK/RMii1_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D14"),
		SUNXI_FUNCTION(0x3, "LVDS3_D2P"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXD3/RMii1_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D15"),
		SUNXI_FUNCTION(0x3, "LVDS3_D2N"),
		SUNXI_FUNCTION(0x5, "RGMMII1_TXD2/RMii1_null"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D16"),
		SUNXI_FUNCTION(0x3, "LVDS3_CKP"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 17),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D17"),
		SUNXI_FUNCTION(0x3, "LVDS3_CKN"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 17),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 18),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D18"),
		SUNXI_FUNCTION(0x3, "LVDS3_D3P"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 18),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 19),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D19"),
		SUNXI_FUNCTION(0x3, "LVDS3_D3N"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 19),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 20),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D20"),
		SUNXI_FUNCTION(0x3, "UART2_TX"),
		SUNXI_FUNCTION(0x4, "UART3_RTS"),
		SUNXI_FUNCTION(0x5, "SPI0_CS0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 20),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 21),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D21"),
		SUNXI_FUNCTION(0x3, "UART2_RX"),
		SUNXI_FUNCTION(0x4, "UART3_CTS"),
		SUNXI_FUNCTION(0x5, "SPI0_CLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 21),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 22),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D22"),
		SUNXI_FUNCTION(0x3, "UART2_RTS"),
		SUNXI_FUNCTION(0x4, "UART3_TX"),
		SUNXI_FUNCTION(0x5, "SPI0_MOSI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 22),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 23),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_D23"),
		SUNXI_FUNCTION(0x3, "UART2_CTS"),
		SUNXI_FUNCTION(0x4, "UART3_RX"),
		SUNXI_FUNCTION(0x5, "SPI0_MISO"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 23),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 24),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_CLK"),
		SUNXI_FUNCTION(0x3, "I2C4_SCL"),
		SUNXI_FUNCTION(0x4, "UART4_TX"),
		SUNXI_FUNCTION(0x5, "SPI0_CSI"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 24),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 25),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_DE"),
		SUNXI_FUNCTION(0x3, "I2C4_SDA"),
		SUNXI_FUNCTION(0x4, "UART4_RX"),
		SUNXI_FUNCTION(0x5, "SPI0_WP"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 25),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 26),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_HSYNC"),
		SUNXI_FUNCTION(0x3, "I2C5_SCL"),
		SUNXI_FUNCTION(0x4, "UART4_RTS"),
		SUNXI_FUNCTION(0x5, "SPI0_HOLD"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 26),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(J, 27),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "LCD1_VSYNC"),
		SUNXI_FUNCTION(0x3, "I2C5_SDA"),
		SUNXI_FUNCTION(0x4, "UART4_CTS"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 8, 27),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	
	/* banks K */
	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 0),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_D0N"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 0),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 1),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_D0P"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 1),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 2),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_D1N"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 2),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 3),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_D1P"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 3),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 4),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_CKN"),
		SUNXI_FUNCTION(0x3, "I2C2_SCL"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 4),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 5),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIA_CKP"),
		SUNXI_FUNCTION(0x3, "I2C2_SDA"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 5),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 6),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_D0N"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 6),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 7),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_D0P"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 7),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 8),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_D1N"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 8),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 9),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_D1P"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 9),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 10),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_CKN"),
		SUNXI_FUNCTION(0x3, "I2C3_SCL"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 10),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 11),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIB_CKP"),
		SUNXI_FUNCTION(0x3, "I2C3_SDA"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 11),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 12),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_D0N"),
		SUNXI_FUNCTION(0x3, "UART7_TX"),
		SUNXI_FUNCTION(0x4, "I2C4_SCL"),
		SUNXI_FUNCTION(0x5, "NCSI_PCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 12),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 13),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_C0N"),
		SUNXI_FUNCTION(0x3, "UART7_RX"),
		SUNXI_FUNCTION(0x4, "I2C4_SCL"),
		SUNXI_FUNCTION(0x5, "NCSI_PCLK"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 13),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 14),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_D1N"),
		SUNXI_FUNCTION(0x3, "UART7_RTS"),
		SUNXI_FUNCTION(0x4, "I2C4_RTS"),
		SUNXI_FUNCTION(0x5, "NCSI_HSYNC"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 14),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 15),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_D1P"),
		SUNXI_FUNCTION(0x3, "UART7_CTS"),
		SUNXI_FUNCTION(0x4, "UART5_CTS"),
		SUNXI_FUNCTION(0x5, "NCSI_VSYNC"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 15),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 16),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_CKN"),
		SUNXI_FUNCTION(0x3, "I2C5_SCL"),
		SUNXI_FUNCTION(0x4, "UART5_TX"),
		SUNXI_FUNCTION(0x5, "NCSI_D0"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 16),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 17),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_CKP"),
		SUNXI_FUNCTION(0x3, "I2C5_SDA"),
		SUNXI_FUNCTION(0x4, "UART5_RX"),
		SUNXI_FUNCTION(0x5, "NCSI_D1"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 17),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 18),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCIC_D0N"),
		SUNXI_FUNCTION(0x3, "MIPI_MCLK0"),
		SUNXI_FUNCTION(0x4, "UART6_TX"),
		SUNXI_FUNCTION(0x5, "NCSI_D2"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 18),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 19),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCID_D0P"),
		SUNXI_FUNCTION(0x3, "I2C2_SCL"),
		SUNXI_FUNCTION(0x4, "UART6_RX"),
		SUNXI_FUNCTION(0x5, "NCSI_D3"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 19),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 20),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCID_D1N"),
		SUNXI_FUNCTION(0x3, "I2C2_SDA"),
		SUNXI_FUNCTION(0x4, "UART6_RTS"),
		SUNXI_FUNCTION(0x5, "NCSI_D4"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 20),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 21),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCID_D1P"),
		SUNXI_FUNCTION(0x3, "MIPI_MCLK1"),
		SUNXI_FUNCTION(0x4, "UART6_CTS"),
		SUNXI_FUNCTION(0x5, "NCSI_D5"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 21),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 22),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCID_CKN"),
		SUNXI_FUNCTION(0x3, "I2C3_SCL"),
		SUNXI_FUNCTION(0x4, "PWM0-6"),
		SUNXI_FUNCTION(0x5, "NCSI_D6"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 22),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

	SUNXI_PIN(SUNXI_PINCTRL_PIN(K, 23),
		SUNXI_FUNCTION(0x0, "IN"),		
		SUNXI_FUNCTION(0x1, "OUT"),	
		SUNXI_FUNCTION(0x2, "MSCID_CKP"),
		SUNXI_FUNCTION(0x3, "I2C3_SDA"),
		SUNXI_FUNCTION(0x4, "PWM0-7"),
		SUNXI_FUNCTION(0x5, "NCSI_D7"),
		SUNXI_FUNCTION_IRQ_BANK(0XE, 9, 23),	/* eint */
		SUNXI_FUNCTION(0xf, "OFF")),	

};

static const unsigned int sun55iw3_irq_bank_map[] = {
	SUNXI_BANK_OFFSET('B', 'A'),
	SUNXI_BANK_OFFSET('C', 'A'),
	SUNXI_BANK_OFFSET('D', 'A'),
	SUNXI_BANK_OFFSET('E', 'A'),
	SUNXI_BANK_OFFSET('F', 'A'),
	SUNXI_BANK_OFFSET('G', 'A'),
	SUNXI_BANK_OFFSET('H', 'A'),
	SUNXI_BANK_OFFSET('I', 'A'),
	SUNXI_BANK_OFFSET('J', 'A'),
	SUNXI_BANK_OFFSET('K', 'A'),
};
/* Describe which bank use vcc-io */
static const unsigned int sun55iw3_vccio_banks[] = {
	SUNXI_BANK_OFFSET('B', 'A'),
	SUNXI_BANK_OFFSET('H', 'A'),
};

static const unsigned int sun55iw3_bank_base[] = {
	SUNXI_BANK_OFFSET('B', 'A'),
	SUNXI_BANK_OFFSET('C', 'A'),
	SUNXI_BANK_OFFSET('D', 'A'),
	SUNXI_BANK_OFFSET('E', 'A'),
	SUNXI_BANK_OFFSET('F', 'A'),
	SUNXI_BANK_OFFSET('G', 'A'),
	SUNXI_BANK_OFFSET('H', 'A'),
	SUNXI_BANK_OFFSET('I', 'A'),
	SUNXI_BANK_OFFSET('J', 'A'),
	SUNXI_BANK_OFFSET('K', 'A'),
};

const struct sunxi_pinctrl_desc sun55iw3_pinctrl_data = {
	.pins = sun55iw3_pins,
	.npins = ARRAY_SIZE(sun55iw3_pins),
	// .banks = ARRAY_SIZE(sun55iw3_bank_base),
	// .bank_base = sun55iw3_bank_base,
	.irq_banks = ARRAY_SIZE(sun55iw3_irq_bank_map),
	.irq_bank_map = sun55iw3_irq_bank_map,
	// .vccio_banks = sun55iw3_vccio_banks,
	// .vccio_nbanks = ARRAY_SIZE(sun55iw3_vccio_banks),
	// .io_bias_cfg_variant = BIAS_VOLTAGE_PIO_POW_MODE_CTL_V2,
	// .pf_power_source_switch = true,
	.hw_type = SUNXI_PCTL_HW_TYPE_3,
};

// /* PINCTRL power management code */
// #if IS_ENABLED(CONFIG_PM_SLEEP)

// static void *mem;
// static int mem_size;

// static int pinctrl_pm_alloc_mem(struct platform_device *pdev)
// {
// 	struct resource *res;

// 	res = platform_get_resource(pdev, IORESOURCE_MEM, 0);
// 	if (!res)
// 		return -EINVAL;
// 	mem_size = resource_size(res);

// 	if (mem) {
// 		sunxi_err(&pdev->dev, "alloc standby mem repeatedly\n");
// 		return -EINVAL;
// 	}
// 	mem = devm_kzalloc(&pdev->dev, mem_size, GFP_KERNEL);
// 	if (!mem)
// 		return -ENOMEM;
// 	return 0;
// }

// static int sun55iw3_pinctrl_suspend_noirq(struct device *dev)
// {
// 	struct sunxi_pinctrl *pctl = dev_get_drvdata(dev);
// 	unsigned long flags;

// 	sunxi_info(dev, "pinctrl suspend\n");

// 	raw_spin_lock_irqsave(&pctl->lock, flags);
// 	memcpy_fromio(mem, pctl->membase, mem_size);
// 	raw_spin_unlock_irqrestore(&pctl->lock, flags);

// 	return 0;
// }

// static int sun55iw3_pinctrl_resume_noirq(struct device *dev)
// {
// 	struct sunxi_pinctrl *pctl = dev_get_drvdata(dev);
// 	unsigned long flags;
// 	uint32_t OFFset, size;
// 	int i;

// 	for (i = 0; i < pctl->desc->irq_banks; i++) {
// 		if (!pctl->ignore_irq[i])
// 			continue;
// 		OFFset = sunxi_irq_regs_from_bank(pctl->desc, i);
// 		size = sunxi_irq_regs_size_from_bank(pctl->desc, i);
// 		memcpy_fromio(mem + OFFset, pctl->membase + OFFset, size);
// 	}

// 	raw_spin_lock_irqsave(&pctl->lock, flags);
// 	memcpy_toio(pctl->membase, mem, mem_size);
// 	raw_spin_unlock_irqrestore(&pctl->lock, flags);

// 	sunxi_info(dev, "pinctrl resume\n");

// 	return 0;
// }

// static const struct dev_pm_ops sun55iw3_pinctrl_pm_ops = {
// 	.suspend_noirq = sun55iw3_pinctrl_suspend_noirq,
// 	.resume_noirq = sun55iw3_pinctrl_resume_noirq,
// };
// #define PINCTRL_PM_OPS	(&sun55iw3_pinctrl_pm_ops)

// #else
// static int pinctrl_pm_alloc_mem(struct platform_device *pdev)
// {
// 	return 0;
// }
// #define PINCTRL_PM_OPS	NULL
// #endif

// static int sun55iw3_pinctrl_probe(struct platform_device *pdev)
// {
// 	int ret;
// 	ret = pinctrl_pm_alloc_mem(pdev);
// 	if (ret) {
// 		sunxi_err(&pdev->dev, "alloc pm mem err\n");
// 		return ret;
// 	}
// #if IS_ENABLED(CONFIG_PINCTRL_SUNXI_DEBUGFS)
// 	dev_set_name(&pdev->dev, "pio");
// #endif
// 	return sunxi_bsp_pinctrl_init(pdev, &sun55iw3_pinctrl_data);
// }

// static struct of_device_id sun55iw3_pinctrl_match[] = {
// 	{ .compatible = "allwinner,sun55iw3-pinctrl", },
// 	{ .compatible = "allwinner,sun20iw1-pinctrl", },
// 	{}
// };

// MODULE_DEVICE_TABLE(of, sun55iw3_pinctrl_match);

// static struct platform_driver sun55iw3_pinctrl_driver = {
// 	.probe	= sun55iw3_pinctrl_probe,
// 	.driver	= {
// 		.name		= "sun55iw3-pinctrl",
// 		.pm		= PINCTRL_PM_OPS,
// 		.of_match_table	= sun55iw3_pinctrl_match,
// 	},
// };

// static int __init sun55iw3_pio_init(void)
// {
// 	return platform_driver_register(&sun55iw3_pinctrl_driver);
// }
// fs_initcall(sun55iw3_pio_init);

// MODULE_DESCRIPTION("Allwinner sun55iw3 pio pinctrl driver");
// MODULE_AUTHOR("<liujuan1@allwinnertech>");
// MODULE_LICENSE("GPL");
// MODULE_VERSION("1.1.6");
