#!/bin/bash
PATH_PWD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

systemctl stop gpioc-server.service
systemctl disable gpioc-server.service
rm /lib/walnutpi/gpioc-server 
rm /lib/systemd/system/gpioc-server.service


